package com.example.helloworld.english;

import java.util.Arrays;
import java.util.List;

public interface Common {
    List<String> files = Arrays.asList(
            "/Users/mark/Desktop/note/English/1200-1.md",
            "/Users/mark/Desktop/note/English/1200-2.md",
            "/Users/mark/Desktop/note/English/1200-3.md",
            "/Users/mark/Desktop/note/English/1200-4.md",
            "/Users/mark/Desktop/note/English/1200-5.md",
            "/Users/mark/Desktop/note/English/1200-6.md",
            "/Users/mark/Desktop/note/English/1200-7.md",
            "/Users/mark/Desktop/note/English/1278-1.md",
            "/Users/mark/Desktop/note/English/1278-2.md",
            "/Users/mark/Desktop/note/English/1278-3.md",
            "/Users/mark/Desktop/note/English/1278-4.md",
            "/Users/mark/Desktop/note/English/1278-5.md",
            "/Users/mark/Desktop/note/English/1278-6.md",
            "/Users/mark/Desktop/note/English/3000-1.md",
            "/Users/mark/Desktop/note/English/3000-2.md",
            "/Users/mark/Desktop/note/English/3000-3.md",
            "/Users/mark/Desktop/note/English/3000-4.md",
            "/Users/mark/Desktop/note/English/3000-5.md",
            "/Users/mark/Desktop/note/English/3000-6.md",
            "/Users/mark/Desktop/note/English/3000-7.md",
            "/Users/mark/Desktop/note/English/3000-8.md",
            "/Users/mark/Desktop/note/English/3000-9.md",
            "/Users/mark/Desktop/note/English/3000-10.md",
            "/Users/mark/Desktop/note/English/3000-11.md",
            "/Users/mark/Desktop/note/English/3000-12.md",
            "/Users/mark/Desktop/note/English/GaoZhong_1.md",
            "/Users/mark/Desktop/note/English/GaoZhong_2.md",
            "/Users/mark/Desktop/note/English/GaoZhong_3.md",
            "/Users/mark/Desktop/note/English/GaoZhong_4.md",
            "/Users/mark/Desktop/note/English/GaoZhong_5.md",
            "/Users/mark/Desktop/note/English/GaoZhong_6.md",
            "/Users/mark/Desktop/note/English/GaoZhong_7.md",
            "/Users/mark/Desktop/note/English/GaoZhong_8.md",
            "/Users/mark/Desktop/note/English/GaoZhong_9.md",
            "/Users/mark/Desktop/note/English/GaoZhong_10.md",
            "/Users/mark/Desktop/note/English/GaoZhong_11.md",
            "/Users/mark/Desktop/note/English/GaoZhong_12.md",
            "/Users/mark/Desktop/note/English/GaoZhong_13.md",
            "/Users/mark/Desktop/note/English/GaoZhong_14.md",
            "/Users/mark/Desktop/note/English/GaoZhong_15.md",
            "/Users/mark/Desktop/note/English/GaoZhong_16.md",
            "/Users/mark/Desktop/note/English/GaoZhong_17.md",
            "/Users/mark/Desktop/note/English/GaoZhong_18.md",
            "/Users/mark/Desktop/note/English/GaoZhong_19.md",
            "/Users/mark/Desktop/note/English/GaoZhong_20.md",
            "/Users/mark/Desktop/note/English/GaoZhong_21.md",
            "/Users/mark/Desktop/note/English/GaoZhong_22.md",
            "/Users/mark/Desktop/note/English/GaoZhong_23.md",
            "/Users/mark/Desktop/note/English/GaoZhong_24.md");
}
